# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 13:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
                ('telefone', models.CharField(max_length=15, verbose_name='telefone')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='lojista',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Lojista',
        ),
    ]
